# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 11:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('country', models.CharField(blank=True, max_length=128)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('city_image', models.ImageField(blank=True, upload_to='city_pictures')),
                ('slug', models.SlugField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_search_text', models.CharField(blank=True, max_length=300)),
                ('message', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visited_city', to='excurj.City')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('traveler_approval', models.NullBooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('local_approval', models.NullBooleanField(default=None)),
            ],
            options={
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('city_search_text', models.CharField(blank=True, max_length=300)),
                ('prof_pic', models.ImageField(blank=True, upload_to='profile_pictures')),
                ('dob', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=10)),
                ('education', models.CharField(blank=True, max_length=200)),
                ('career', models.CharField(blank=True, max_length=200)),
                ('about_you', models.CharField(blank=True, max_length=500)),
                ('music_movies_books', models.CharField(blank=True, max_length=1000)),
                ('friendship', models.CharField(blank=True, max_length=500)),
                ('what_will_you_show_visitors', models.CharField(blank=True, max_length=1000)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='excurj.City')),
            ],
        ),
        migrations.CreateModel(
            name='RequestReference',
            fields=[
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reference_request', serialize=False, to='excurj.Request')),
                ('traveler_desc', models.CharField(blank=True, max_length=500)),
                ('local_desc', models.CharField(blank=True, max_length=500)),
                ('traveler_fun', models.BooleanField(default=True)),
                ('local_fun', models.BooleanField(default=True)),
            ],
            options={
                'get_latest_by': 'request_id',
            },
        ),
        migrations.AddField(
            model_name='request',
            name='local',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='traveler',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='traveler_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_offers_excursion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traveler_trip', to='excurj.Excursion'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_who_offered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='excursion',
            name='traveler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traveler_lists_excursion', to=settings.AUTH_USER_MODEL),
        ),
    ]
