# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excurj', '0002_auto_20170407_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_id',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
