# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excurj', '0003_auto_20170407_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sex',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friendship',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
