# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excurj', '0004_auto_20170414_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
