# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excurj', '0006_auto_20170414_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='excurj.City'),
        ),
    ]
