# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excurj', '0011_auto_20170508_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='traveler',
        ),
        migrations.AddField(
            model_name='excursion',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visited_city', to='excurj.City'),
        ),
    ]
