# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excurj', '0014_auto_20170514_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='local_person',
            new_name='local',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='local_person',
            new_name='local',
        ),
    ]
