# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 15:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excurj', '0015_auto_20170514_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'get_latest_by': 'date'},
        ),
        migrations.AddField(
            model_name='reference',
            name='date',
            field=models.DateField(default=datetime.date(2017, 5, 14)),
        ),
    ]
