# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 19:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excurj', '0016_auto_20170514_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='local',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 14, 22, 8, 14, 810426)),
        ),
        migrations.AlterField(
            model_name='reference',
            name='description',
            field=models.CharField(default='default reference', max_length=500),
        ),
    ]
