# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 10:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excurj', '0023_auto_20170515_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 15, 13, 5, 48, 603884)),
        ),
    ]
