# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 17:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excurj', '0036_auto_20170516_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='local',
            new_name='is_local',
        ),
        migrations.AlterField(
            model_name='reference',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 16, 20, 56, 20, 931834)),
        ),
    ]
