# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 18:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excurj', '0038_auto_20170516_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='is_local',
            new_name='local',
        ),
        migrations.AlterField(
            model_name='reference',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 16, 21, 4, 14, 588650)),
        ),
    ]
