# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excurj', '0043_auto_20170517_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='local_approval',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='requestreference',
            name='local_fun',
            field=models.BooleanField(default=True),
        ),
    ]
