# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excurj', '0045_auto_20170524_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='excurj.City'),
        ),
    ]
