# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excurj', '0047_userprofile_city_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='city_text',
            new_name='city_search_text',
        ),
    ]
