# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 22:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excurj', '0049_auto_20170525_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='local',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='local_approval',
            field=models.BooleanField(),
        ),
    ]
