# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excurj', '0052_auto_20170531_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='city_search_text',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
