# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excurj', '0053_excursion_city_search_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='traveler_approval',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='offer',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traveler_trip', to='excurj.Excursion'),
        ),
    ]
