# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excurj', '0054_auto_20170601_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='traveler_approval',
            field=models.NullBooleanField(default=None),
        ),
    ]
