# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excurj', '0055_auto_20170601_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='music_movies_books',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
