# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 14:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('excurj', '0056_auto_20170603_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_who_offered', to=settings.AUTH_USER_MODEL),
        ),
    ]
