# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excurj', '0057_excursion_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
