# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excurj', '0059_auto_20170606_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
