# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excurj', '0060_auto_20170606_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestreference',
            options={'get_latest_by': 'request_id'},
        ),
    ]
