# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excurj', '0062_auto_20170612_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='local_approval',
            field=models.NullBooleanField(default=None),
        ),
    ]
