# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excurj', '0063_auto_20170612_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'get_latest_by': 'id'},
        ),
    ]
